services:
  db:
    image: postgres:15-alpine3.18
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    expose:
      - 5432

volumes:
  pgdata:
    # driver: local
