from app import app
from domain.business_logic.operations.tests.test_addition import *
from domain.business_logic.operations.tests.test_division import *
from domain.business_logic.operations.tests.test_multiplication import *
from domain.business_logic.operations.tests.test_random_string_generation import *
from domain.business_logic.operations.tests.test_square_root import *
from domain.business_logic.operations.tests.test_subtraction import *
from domain.business_logic.tests.test_operation_factory import *
from domain.business_logic.tests.test_calculator import *
from domain.business_logic.tests.test_operation_manager import *
from domain.business_logic.services.tests.test_user_service import *